from pyglet.gl import (
glAttachShader as AttachShader,
glBindBuffer as BindBuffer,
glBindVertexArray as BindVertexArray,
glBufferData as BufferData,
glClearColor as ClearColor,
glCompileShader as CompileShader,
glCreateProgram as CreateProgram,
glCreateShader as CreateShader,
glDrawElementsInstanced as DrawElementsInstanced,
glEnableVertexAttribArray as EnableVertexAttribArray,
glGenBuffers as GenBuffers,
glGenVertexArrays as GenVertexArrays,
glGetActiveAttrib as GetActiveAttrib,
glGetActiveUniform as GetActiveUniform,
glGetAttribLocation as GetAttribLocation,
glGetProgramInfoLog as GetProgramInfoLog,
glGetProgramiv as GetProgramiv,
glGetShaderInfoLog as GetShaderInfoLog,
glGetShaderiv as GetShaderiv,
glGetUniformfv as GetUniformfv,
glGetUniformiv as GetUniformiv,
glLinkProgram as LinkProgram,
glShaderSource as ShaderSource,
glUniform1f as Uniform1f,
glUniform1i as Uniform1i,
glUniform2f as Uniform2f,
glUniform2i as Uniform2i,
glUniform3f as Uniform3f,
glUniform3i as Uniform3i,
glUniform4f as Uniform4f,
glUniform4i as Uniform4i,
glUseProgram as UseProgram,
glVertexAttribDivisor as VertexAttribDivisor,
glVertexAttribPointer as VertexAttribPointer,
GLboolean,
GLbyte,
GLenum,
GLfloat,
GLint,
GLshort,
GLsizei,
GLubyte,
GLuint,
GLushort,
GL_ACTIVE_UNIFORMS,
GL_ARRAY_BUFFER,
GL_BOOL,
GL_BOOL_VEC2,
GL_BOOL_VEC3,
GL_BOOL_VEC4,
GL_BYTE,
GL_ELEMENT_ARRAY_BUFFER,
GL_FALSE,
GL_FLOAT,
GL_FLOAT_MAT2,
GL_FLOAT_MAT3,
GL_FLOAT_MAT4,
GL_FLOAT_VEC2,
GL_FLOAT_VEC3,
GL_FLOAT_VEC4,
GL_FRAGMENT_SHADER,
GL_INFO_LOG_LENGTH,
GL_INT,
GL_INT_VEC2,
GL_INT_VEC3,
GL_INT_VEC4,
GL_LINK_STATUS,
GL_OBJECT_COMPILE_STATUS_ARB,
GL_SHORT,
GL_STATIC_DRAW,
GL_STREAM_DRAW,
GL_STREAM_READ,
GL_TRIANGLES,
GL_UNSIGNED_BYTE,
GL_UNSIGNED_INT,
GL_UNSIGNED_SHORT,
GL_VERTEX_SHADER,
)
